### ISSUE TITLE
dblclickDuplicateTab.uc.js not working on FF 69

### ISSUE THREAD

**Issue by roaminghawk** [tkhquang/userChrome.js#1]
Hi,

dblclickDuplicateTab stopped working on FF 69.

Thanks

**Comment by tkhquang** [comment]
Hello @roaminghawk, I have just updated the file for FF69, sorry for taking this so long. Github didn't notify me about this issue for some reasons... :sweat_smile: 

https://github.com/tkhquang/userChrome.js/commit/c5d9faf60c8665747ba1295b0f03d2600c317f0a#diff-d2e937650f2e7e92f823cee833d5c119
