### ISSUE TITLE
Don't work on FIrefox 125.0b8

### ISSUE THREAD

**Issue by actforjason** [tkhquang/userChrome.js#2]
titlebar_movable.uc.js does not work.

**Comment by tkhquang** [comment]
> titlebar_movable.uc.js does not work.

Thanks for reporting, I will investigate the issue ASAP

**Comment by tkhquang** [comment]
Hello @actforjason 
I have updated the script to work with the latest Firefox f7221524ebbd4f21092318cdc91b01fd0ad6b20a

Basically they have changed the way how we should import `Services` in our script. Please take look at the script to see if it's ok now.

**Comment by actforjason** [comment]
It runs very well, thank you for your work.
